### ISSUE TITLE
Can't initialize setup.sh

### ISSUE THREAD

**Issue by blazepsyki** [platformxlab/LeaFTL#2]
i tried to follow README.md, but failed with the following message:

gth1919@psyki-server:~/LeaFTL/wiscsee/leaftl_scripts$ ./setup.sh 
Requirement already satisfied: psutil in /home/gth1919/.local/lib/python3.8/site-packages (5.9.5)
Requirement already satisfied: simpy in /home/gth1919/.local/lib/python3.8/site-packages (4.0.1)
Requirement already satisfied: bitarray in /home/gth1919/.local/lib/python3.8/site-packages (2.7.3)
Requirement already satisfied: bidict in /home/gth1919/.local/lib/python3.8/site-packages (0.22.1)
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting scipy
  Using cached scipy-1.2.3.tar.gz (23.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/bin/pypy -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ChBeWR/scipy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ChBeWR/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ChBeWR/scipy/pip-egg-info
         cwd: /tmp/pip-install-ChBeWR/scipy/
    Complete output (55 lines):
    WARNING: The wheel package is not available.
    DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
      ERROR: Command errored out with exit status 1:
       command: /home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/bin/pypy -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-2Uh9u7/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-2Uh9u7/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hf4dar
           cwd: /tmp/pip-wheel-2Uh9u7/numpy/
      Complete output (7 lines):
      Running from numpy source directory.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for numpy
      ERROR: Command errored out with exit status 1:
       command: /home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/bin/pypy -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-2Uh9u7/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-2Uh9u7/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
           cwd: /tmp/pip-wheel-2Uh9u7/numpy
      Complete output (10 lines):
      Running from numpy source directory.
    
      `setup.py clean` is not supported, use one of the following instead:
    
        - `git clean -xdf` (cleans all files)
        - `git clean -Xdf` (cleans all versioned files, doesn't touch
                            files that aren't checked into the git repo)
    
      Add `--force` to your command to use it anyway if you must (unsupported).
    
      ----------------------------------------
      ERROR: Failed cleaning build dir for numpy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-install-ChBeWR/scipy/setup.py", line 492, in <module>
        setup_package()
      File "/tmp/pip-install-ChBeWR/scipy/setup.py", line 488, in setup_package
        setup(**metadata)
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    DistutilsError: Command '['/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/bin/pypy', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp3l5Omb', '--quiet', 'numpy>=1.8.2']' returned non-zero exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/home/gth1919/LeaFTL/wiscsee/leaftl_scripts/pypy2.7-v7.3.9-linux64/bin/pypy -m pip install --upgrade pip' command.

Can I get infos for fixing these errors?

**Comment by yeojin5** [comment]
did you solve it?
I solved it because I used pypy3.

**Comment by gholamreza-askary** [comment]
> did you solve it? I solved it because I used pypy3.

hello
I have that problem.
how I can use this simulator with pypy3 or python3 ?
thanks

**Comment by yeojin5** [comment]
> > did you solve it? I solved it because I used pypy3.
> 
> hello I have that problem. how I can use this simulator with pypy3 or python3 ? thanks

You need to first activate the Python 3.8 virtual environment, then install pypy2. After that, run the setup.sh script. It should work successfully!

**Comment by yeojin5** [comment]
`pypy -m pip install psutil simpy bitarray bidict
pypy -m pip install wheel scipy mmh3 objgraph`
try this code... I could set up with this code
